### ISSUE TITLE
Request for adding 'platform' parameter to the  parse_genie filter plugin

### ISSUE THREAD

**Issue by TheFly1ngDutch** [clay584/genie_collection#1]
Would it be possible to add the "platform=" below along with the "command" and "os"

"{{ show_cli_output | clay584.genie.parse_genie(command='show version', os='iosxe') }}"

That would help genie select platform specific parsers if available.

Thanks for your help.

**Comment by tahigash** [comment]
Opened PR to support `platform`.

https://github.com/clay584/genie_collection/pull/2

@clay584 could you please review above PR?

**Comment by clay584** [comment]
merged
